# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-03 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athletes_name', models.CharField(max_length=30)),
                ('athletes_id', models.CharField(max_length=30)),
                ('athletes_age', models.IntegerField()),
                ('team_type', models.IntegerField()),
                ('event_type', models.CharField(max_length=30)),
                ('athletes_sex', models.IntegerField()),
                ('athletes_number', models.IntegerField()),
            ],
            options={
                'db_table': 'learn_Athlete',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('leader_name', models.CharField(max_length=30)),
                ('leader_id', models.CharField(max_length=30)),
                ('leader_telephone', models.CharField(max_length=30)),
                ('doctor_name', models.CharField(max_length=30)),
                ('doctor_id', models.CharField(max_length=30)),
                ('doctor_telephone', models.CharField(max_length=30)),
                ('coach_name', models.CharField(max_length=30)),
                ('coach_id', models.CharField(max_length=30)),
                ('coach_telephone', models.CharField(max_length=30)),
                ('coach_sex', models.IntegerField()),
                ('referee_name', models.CharField(max_length=30)),
                ('referee_id', models.CharField(max_length=30)),
                ('referee_telephone', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='athlete',
            unique_together=set([('athletes_number', 'event_type')]),
        ),
    ]
