# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_person_final_person_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='person_final',
            name='athletes_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='person_first',
            name='athletes_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
