# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_auto_20180105_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='referee_password',
            field=models.CharField(default='', max_length=30),
        ),
    ]
